language: go

os:
  - linux
  - osx

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.4
  - 1.6
  - 1.7
  - 1.8
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - go get -t ./...

script:
  - go test ./... -v -short -covermode=count -coverprofile=cover.out
  - $HOME/gopath/bin/goveralls -service=travis-ci
